import Foundation
import Observation
import os
import Security

// import DropFfi  // Uncomment once the DropFfi.xcframework is built and linked.
//
// The DropFfi module is generated by UniFFI from the Rust `drop-ffi` crate.
// Build the Rust target first:
//   cargo build -p drop-ffi --target aarch64-apple-ios --release
// Then add the generated DropFfi.xcframework to the Xcode project and uncomment
// the import above. All references to DropCore / Ffi* types will resolve.

/// Bridges the Rust `drop-core` library (via UniFFI) to the iOS app.
/// All protocol logic — identity, message encoding, Bloom filters — lives in Rust.
/// This class exposes a Swift-friendly API and holds observable state for the UI.
@Observable
final class DropRepository: @unchecked Sendable {

    private let logger = Logger(subsystem: "com.drop", category: "DropRepository")

    /// The Rust core engine. All cryptographic and protocol operations delegate here.
    private let core: DropCore

    // MARK: - Peer Mapping

    /// Maps CoreBluetooth peripheral UUIDs → Rust-level device IDs.
    /// Populated during the BLE handshake phase.
    private var peerDeviceIds: [UUID: Data] = [:]

    /// Reverse map: Rust device ID → CoreBluetooth UUID (for building conversations).
    private var deviceIdToPeerId: [Data: UUID] = [:]

    // MARK: - Local Message Store

    /// In-memory message history keyed by conversation (peer) UUID.
    /// TODO: Persist message history to disk so it survives app restarts.
    private var messageStore: [UUID: [ChatMessage]] = [:]

    // MARK: - Published State

    var conversations: [Conversation] = []
    var currentMessages: [ChatMessage] = []

    // MARK: - Initialization

    init() {
        let dbPath = Self.databasePath()
        let secretKey = KeychainHelper.loadSecretKey()

        do {
            core = try DropCore.new(dbPath: dbPath, secretKey: secretKey)

            // On first launch the core generates a new identity.
            // Persist the secret key so subsequent launches reuse it.
            if secretKey == nil {
                let identity = core.getIdentity()
                KeychainHelper.storeSecretKey(identity.secretKey)
            }

            logger.info("DropCore initialized (db: \(dbPath))")
        } catch {
            fatalError("Failed to initialize DropCore: \(error)")
        }
    }

    // MARK: - Identity

    /// Returns this device's persistent Rust-level device ID.
    func getIdentity() -> Data {
        core.getDeviceId()
    }

    // MARK: - Bloom Filter

    /// Builds a Bloom filter representing the set of peer IDs this device has
    /// pending messages for. Advertised in BLE service data so remote peers
    /// can quickly decide whether a connection is worthwhile.
    func buildBloomFilter() -> Data {
        do {
            return try core.buildBloomFilter()
        } catch {
            logger.error("buildBloomFilter failed: \(error)")
            return Data()
        }
    }

    /// Checks whether a remote Bloom filter indicates the peer may have
    /// messages for us.
    func checkBloomFilter(remoteFilter: Data?) -> Bool {
        guard let filter = remoteFilter else { return false }
        return core.checkBloomFilter(filterBytes: filter)
    }

    // MARK: - Handshake

    /// Builds a handshake payload addressed to a specific peer.
    /// Returns empty `Data` if the peer's Rust device ID is not yet known
    /// (i.e. we haven't received their handshake yet).
    func buildHandshake(peerId: UUID) -> Data {
        guard let deviceId = peerDeviceIds[peerId] else {
            // TODO: Define an initial "hello" handshake that doesn't require
            //       the remote device ID (first contact scenario).
            logger.warning("No device ID mapped for peer \(peerId); cannot build targeted handshake")
            return Data()
        }

        do {
            return try core.buildHandshake(peerDeviceId: deviceId)
        } catch {
            logger.error("buildHandshake failed for \(peerId): \(error)")
            return Data()
        }
    }

    /// Parses an incoming handshake, stores the BLE ↔ Rust device-ID mapping,
    /// and logs the list of pending message IDs the remote peer advertised.
    func processHandshake(_ data: Data, from peerId: UUID) {
        do {
            let info = try core.parseHandshake(data: data)

            peerDeviceIds[peerId] = info.deviceId
            deviceIdToPeerId[info.deviceId] = peerId

            logger.info(
                "Handshake from \(peerId): deviceId=\(info.deviceId.hexString), "
                + "version=\(info.version), pendingMsgs=\(info.pendingMsgIds.count)"
            )

            // TODO: Use info.pendingMsgIds to request specific messages from
            //       the remote peer during the transfer phase.
        } catch {
            logger.error("processHandshake failed: \(error)")
        }
    }

    // MARK: - Messages

    /// Returns the wire-encoded pending messages destined for a given BLE peer.
    func getPendingMessages(peerId: UUID) -> [Data] {
        guard let deviceId = peerDeviceIds[peerId] else {
            logger.warning("getPendingMessages: no device ID mapped for peer \(peerId)")
            return []
        }

        do {
            return try core.getPendingForPeer(deviceId: deviceId).map(\.wireBytes)
        } catch {
            logger.error("getPendingMessages failed: \(error)")
            return []
        }
    }

    /// Decrypts and stores an incoming wire-format message received over BLE.
    func storeIncomingMessage(_ data: Data, from peerId: UUID) {
        do {
            let decrypted = try core.receiveMessage(wireBytes: data)

            let conversationId = deviceIdToPeerId[decrypted.senderId] ?? peerId

            let message = ChatMessage(
                id: UUID(msgId: decrypted.msgId),
                conversationID: conversationId,
                text: decrypted.body,
                timestamp: Date(timestampMs: decrypted.timestampMs),
                isOutgoing: false,
                isDelivered: true
            )

            messageStore[conversationId, default: []].append(message)

            // Live-update the UI if the user is viewing this conversation.
            if currentMessages.first?.conversationID == conversationId
                || currentMessages.isEmpty
            {
                currentMessages = messageStore[conversationId] ?? []
            }

            refreshConversations()

            logger.info("Stored incoming message \(decrypted.msgId) from \(peerId)")
        } catch {
            logger.error("storeIncomingMessage failed: \(error)")
        }
    }

    /// Marks messages as delivered in the Rust core and updates the local UI state.
    /// Each element in `messageIds` is expected to be a UTF-8 encoded message-ID string.
    func markDelivered(messageIds: [Data]) {
        for idData in messageIds {
            guard let msgId = String(data: idData, encoding: .utf8) else { continue }
            markDelivered(msgId: msgId)
        }
    }

    /// Marks a single message as delivered by its string ID.
    func markDelivered(msgId: String) {
        do {
            try core.markDelivered(msgId: msgId)
            updateDeliveryStatus(for: msgId)
            logger.debug("Marked delivered: \(msgId)")
        } catch {
            logger.error("markDelivered failed for \(msgId): \(error)")
        }
    }

    // MARK: - Chunking

    /// Splits a wire-encoded message into BLE-MTU–sized chunks for transmission.
    func splitIntoChunks(wireBytes: Data, mtu: UInt16) -> [Data] {
        core.splitIntoChunks(msgWireBytes: wireBytes, mtu: mtu)
    }

    /// Feeds a received chunk into the reassembly engine.
    /// Returns `(true, assembledBytes)` once all chunks for a message have arrived.
    func processChunk(_ chunkBytes: Data) -> (complete: Bool, wireBytes: Data?) {
        do {
            let result = try core.processChunk(chunkBytes: chunkBytes)
            return (result.isComplete, result.assembledMessage)
        } catch {
            logger.error("processChunk failed: \(error)")
            return (false, nil)
        }
    }

    /// Builds a chunk-level ACK to send back to the transmitting peer.
    func buildAck(msgId: String, chunkIndex: UInt16) -> Data? {
        do {
            return try core.buildAck(msgId: msgId, chunkIndex: chunkIndex)
        } catch {
            logger.error("buildAck failed: \(error)")
            return nil
        }
    }

    // MARK: - Peer Management

    /// Manually registers a peer (e.g. from an out-of-band key exchange like QR code).
    func addPeer(publicKey: Data, displayName: String) -> Bool {
        do {
            let peer = try core.addPeer(publicKey: publicKey, displayName: displayName)
            let peerId = UUID(deviceId: peer.deviceId)
            peerDeviceIds[peerId] = peer.deviceId
            deviceIdToPeerId[peer.deviceId] = peerId
            refreshConversations()
            return true
        } catch {
            logger.error("addPeer failed: \(error)")
            return false
        }
    }

    // MARK: - UI Helpers

    func loadConversations() {
        refreshConversations()
    }

    func loadMessages(for conversationID: UUID) {
        currentMessages = messageStore[conversationID] ?? []
    }

    func sendMessage(_ text: String, to conversationID: UUID) {
        guard let deviceId = peerDeviceIds[conversationID] else {
            logger.warning("sendMessage: no device ID mapped for conversation \(conversationID)")
            return
        }

        do {
            let ffiMessage = try core.composeMessage(recipientDeviceId: deviceId, text: text)

            let message = ChatMessage(
                id: UUID(msgId: ffiMessage.msgId),
                conversationID: conversationID,
                text: text,
                timestamp: Date(timestampMs: ffiMessage.timestampMs),
                isOutgoing: true,
                isDelivered: false
            )

            messageStore[conversationID, default: []].append(message)
            currentMessages = messageStore[conversationID] ?? []

            refreshConversations()

            logger.info("Composed message \(ffiMessage.msgId) → \(conversationID)")
        } catch {
            logger.error("sendMessage failed: \(error)")
        }
    }

    // MARK: - Private Helpers

    private func refreshConversations() {
        do {
            let peers = try core.getPeers()
            conversations = peers.map { peer in
                let peerId = deviceIdToPeerId[peer.deviceId] ?? UUID(deviceId: peer.deviceId)
                let messages = messageStore[peerId] ?? []
                let lastMsg = messages.last

                return Conversation(
                    id: peerId,
                    peerName: peer.displayName,
                    lastMessage: lastMsg?.text ?? "",
                    lastMessageDate: lastMsg?.timestamp ?? Date.fromOptionalMs(peer.lastSeen),
                    unreadCount: messages.filter { !$0.isOutgoing && !$0.isDelivered }.count
                )
            }
        } catch {
            logger.error("refreshConversations failed: \(error)")
        }
    }

    private func updateDeliveryStatus(for msgId: String) {
        let targetId = UUID(msgId: msgId)
        for (convId, messages) in messageStore {
            guard let idx = messages.firstIndex(where: { $0.id == targetId }) else { continue }
            let old = messages[idx]
            messageStore[convId]?[idx] = ChatMessage(
                id: old.id,
                conversationID: old.conversationID,
                text: old.text,
                timestamp: old.timestamp,
                isOutgoing: old.isOutgoing,
                isDelivered: true
            )
            if currentMessages.contains(where: { $0.conversationID == convId }) {
                currentMessages = messageStore[convId] ?? []
            }
            return
        }
    }

    private static func databasePath() -> String {
        let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        return docs.appendingPathComponent("drop.sqlite3").path
    }
}

// MARK: - Keychain Helper

/// Stores and retrieves the Rust identity secret key in the iOS Keychain.
private enum KeychainHelper {
    static let service = "com.drop.messaging"
    static let account = "identity"

    static func loadSecretKey() -> Data? {
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: account,
            kSecReturnData as String: true,
            kSecMatchLimit as String: kSecMatchLimitOne,
        ]

        var result: AnyObject?
        let status = SecItemCopyMatching(query as CFDictionary, &result)
        guard status == errSecSuccess else { return nil }
        return result as? Data
    }

    static func storeSecretKey(_ key: Data) {
        let deleteQuery: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: account,
        ]
        SecItemDelete(deleteQuery as CFDictionary)

        let addQuery: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: account,
            kSecValueData as String: key,
            kSecAttrAccessible as String: kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly,
        ]

        let status = SecItemAdd(addQuery as CFDictionary, nil)
        if status != errSecSuccess {
            os_log(.error, "Keychain store failed with status %d", status)
        }
    }
}

// MARK: - Type Mapping Extensions

private extension UUID {
    /// Deterministic UUID from a message-ID string (pass-through if already a UUID).
    init(msgId: String) {
        if let uuid = UUID(uuidString: msgId) {
            self = uuid
        } else {
            var bytes = Array(msgId.utf8.prefix(16))
            while bytes.count < 16 { bytes.append(0) }
            self.init(uuid: (
                bytes[0],  bytes[1],  bytes[2],  bytes[3],
                bytes[4],  bytes[5],  bytes[6],  bytes[7],
                bytes[8],  bytes[9],  bytes[10], bytes[11],
                bytes[12], bytes[13], bytes[14], bytes[15]
            ))
        }
    }

    /// Deterministic UUID from a Rust device-ID byte blob (first 16 bytes, zero-padded).
    init(deviceId data: Data) {
        var bytes = [UInt8](data.prefix(16))
        while bytes.count < 16 { bytes.append(0) }
        self.init(uuid: (
            bytes[0],  bytes[1],  bytes[2],  bytes[3],
            bytes[4],  bytes[5],  bytes[6],  bytes[7],
            bytes[8],  bytes[9],  bytes[10], bytes[11],
            bytes[12], bytes[13], bytes[14], bytes[15]
        ))
    }
}

private extension Date {
    init(timestampMs: UInt64) {
        self.init(timeIntervalSince1970: Double(timestampMs) / 1000.0)
    }

    static func fromOptionalMs(_ ms: Int64?) -> Date {
        guard let ms else { return .distantPast }
        return Date(timeIntervalSince1970: Double(ms) / 1000.0)
    }
}

private extension Data {
    /// Hex string for logging (e.g. "a1b2c3…").
    var hexString: String {
        map { String(format: "%02x", $0) }.joined()
    }
}
