// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(drop_ffiFFI)
import drop_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_drop_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_drop_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureDropFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol DropCoreProtocol: AnyObject, Sendable {
    
    func addPeer(publicKey: Data, displayName: String) throws  -> FfiPeer
    
    /**
     * Build a chunk ACK (wire bytes).
     */
    func buildAck(msgId: String, chunkIndex: UInt16) throws  -> Data
    
    /**
     * Build an 8-byte Bloom filter from all pending outbound recipients.
     */
    func buildBloomFilter() throws  -> Data
    
    /**
     * Build a handshake payload for a specific peer.
     */
    func buildHandshake(peerDeviceId: Data) throws  -> Data
    
    /**
     * Check if our device_id is in a remote peer's Bloom filter.
     */
    func checkBloomFilter(filterBytes: Data)  -> Bool
    
    /**
     * Compose, encrypt, store, and return a new outbound message.
     */
    func composeMessage(recipientDeviceId: Data, text: String) throws  -> FfiMessage
    
    func getDeviceId()  -> Data
    
    func getIdentity()  -> FfiIdentity
    
    func getPeers() throws  -> [FfiPeer]
    
    /**
     * Get all queued outbound messages for a peer (as wire bytes).
     */
    func getPendingForPeer(deviceId: Data) throws  -> [FfiMessage]
    
    /**
     * Get device IDs of all peers with pending outbound messages.
     */
    func getPendingRecipients() throws  -> [Data]
    
    func markDelivered(msgId: String) throws 
    
    /**
     * Parse a received handshake payload.
     */
    func parseHandshake(data: Data) throws  -> FfiHandshakeInfo
    
    /**
     * Process a received chunk. Returns result indicating whether the
     * full message has been reassembled.
     */
    func processChunk(chunkBytes: Data) throws  -> FfiChunkResult
    
    /**
     * Decrypt a received message from wire bytes.
     */
    func receiveMessage(wireBytes: Data) throws  -> FfiDecryptedMessage
    
    /**
     * Split a message's wire bytes into MTU-sized chunks (each as wire bytes).
     */
    func splitIntoChunks(msgWireBytes: Data, mtu: UInt16)  -> [Data]
    
}
open class DropCore: DropCoreProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_drop_ffi_fn_clone_dropcore(self.pointer, $0) }
    }
    /**
     * Create or restore a DropCore instance.
     * If `secret_key` is provided (32 bytes), restores that identity.
     * Otherwise, generates a new one.
     */
public convenience init(dbPath: String, secretKey: Data?)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeDropError_lift) {
    uniffi_drop_ffi_fn_constructor_dropcore_new(
        FfiConverterString.lower(dbPath),
        FfiConverterOptionData.lower(secretKey),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_drop_ffi_fn_free_dropcore(pointer, $0) }
    }

    

    
open func addPeer(publicKey: Data, displayName: String)throws  -> FfiPeer  {
    return try  FfiConverterTypeFfiPeer_lift(try rustCallWithError(FfiConverterTypeDropError_lift) {
    uniffi_drop_ffi_fn_method_dropcore_add_peer(self.uniffiClonePointer(),
        FfiConverterData.lower(publicKey),
        FfiConverterString.lower(displayName),$0
    )
})
}
    
    /**
     * Build a chunk ACK (wire bytes).
     */
open func buildAck(msgId: String, chunkIndex: UInt16)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeDropError_lift) {
    uniffi_drop_ffi_fn_method_dropcore_build_ack(self.uniffiClonePointer(),
        FfiConverterString.lower(msgId),
        FfiConverterUInt16.lower(chunkIndex),$0
    )
})
}
    
    /**
     * Build an 8-byte Bloom filter from all pending outbound recipients.
     */
open func buildBloomFilter()throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeDropError_lift) {
    uniffi_drop_ffi_fn_method_dropcore_build_bloom_filter(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Build a handshake payload for a specific peer.
     */
open func buildHandshake(peerDeviceId: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeDropError_lift) {
    uniffi_drop_ffi_fn_method_dropcore_build_handshake(self.uniffiClonePointer(),
        FfiConverterData.lower(peerDeviceId),$0
    )
})
}
    
    /**
     * Check if our device_id is in a remote peer's Bloom filter.
     */
open func checkBloomFilter(filterBytes: Data) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_drop_ffi_fn_method_dropcore_check_bloom_filter(self.uniffiClonePointer(),
        FfiConverterData.lower(filterBytes),$0
    )
})
}
    
    /**
     * Compose, encrypt, store, and return a new outbound message.
     */
open func composeMessage(recipientDeviceId: Data, text: String)throws  -> FfiMessage  {
    return try  FfiConverterTypeFfiMessage_lift(try rustCallWithError(FfiConverterTypeDropError_lift) {
    uniffi_drop_ffi_fn_method_dropcore_compose_message(self.uniffiClonePointer(),
        FfiConverterData.lower(recipientDeviceId),
        FfiConverterString.lower(text),$0
    )
})
}
    
open func getDeviceId() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_drop_ffi_fn_method_dropcore_get_device_id(self.uniffiClonePointer(),$0
    )
})
}
    
open func getIdentity() -> FfiIdentity  {
    return try!  FfiConverterTypeFfiIdentity_lift(try! rustCall() {
    uniffi_drop_ffi_fn_method_dropcore_get_identity(self.uniffiClonePointer(),$0
    )
})
}
    
open func getPeers()throws  -> [FfiPeer]  {
    return try  FfiConverterSequenceTypeFfiPeer.lift(try rustCallWithError(FfiConverterTypeDropError_lift) {
    uniffi_drop_ffi_fn_method_dropcore_get_peers(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get all queued outbound messages for a peer (as wire bytes).
     */
open func getPendingForPeer(deviceId: Data)throws  -> [FfiMessage]  {
    return try  FfiConverterSequenceTypeFfiMessage.lift(try rustCallWithError(FfiConverterTypeDropError_lift) {
    uniffi_drop_ffi_fn_method_dropcore_get_pending_for_peer(self.uniffiClonePointer(),
        FfiConverterData.lower(deviceId),$0
    )
})
}
    
    /**
     * Get device IDs of all peers with pending outbound messages.
     */
open func getPendingRecipients()throws  -> [Data]  {
    return try  FfiConverterSequenceData.lift(try rustCallWithError(FfiConverterTypeDropError_lift) {
    uniffi_drop_ffi_fn_method_dropcore_get_pending_recipients(self.uniffiClonePointer(),$0
    )
})
}
    
open func markDelivered(msgId: String)throws   {try rustCallWithError(FfiConverterTypeDropError_lift) {
    uniffi_drop_ffi_fn_method_dropcore_mark_delivered(self.uniffiClonePointer(),
        FfiConverterString.lower(msgId),$0
    )
}
}
    
    /**
     * Parse a received handshake payload.
     */
open func parseHandshake(data: Data)throws  -> FfiHandshakeInfo  {
    return try  FfiConverterTypeFfiHandshakeInfo_lift(try rustCallWithError(FfiConverterTypeDropError_lift) {
    uniffi_drop_ffi_fn_method_dropcore_parse_handshake(self.uniffiClonePointer(),
        FfiConverterData.lower(data),$0
    )
})
}
    
    /**
     * Process a received chunk. Returns result indicating whether the
     * full message has been reassembled.
     */
open func processChunk(chunkBytes: Data)throws  -> FfiChunkResult  {
    return try  FfiConverterTypeFfiChunkResult_lift(try rustCallWithError(FfiConverterTypeDropError_lift) {
    uniffi_drop_ffi_fn_method_dropcore_process_chunk(self.uniffiClonePointer(),
        FfiConverterData.lower(chunkBytes),$0
    )
})
}
    
    /**
     * Decrypt a received message from wire bytes.
     */
open func receiveMessage(wireBytes: Data)throws  -> FfiDecryptedMessage  {
    return try  FfiConverterTypeFfiDecryptedMessage_lift(try rustCallWithError(FfiConverterTypeDropError_lift) {
    uniffi_drop_ffi_fn_method_dropcore_receive_message(self.uniffiClonePointer(),
        FfiConverterData.lower(wireBytes),$0
    )
})
}
    
    /**
     * Split a message's wire bytes into MTU-sized chunks (each as wire bytes).
     */
open func splitIntoChunks(msgWireBytes: Data, mtu: UInt16) -> [Data]  {
    return try!  FfiConverterSequenceData.lift(try! rustCall() {
    uniffi_drop_ffi_fn_method_dropcore_split_into_chunks(self.uniffiClonePointer(),
        FfiConverterData.lower(msgWireBytes),
        FfiConverterUInt16.lower(mtu),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDropCore: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = DropCore

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> DropCore {
        return DropCore(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: DropCore) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DropCore {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: DropCore, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDropCore_lift(_ pointer: UnsafeMutableRawPointer) throws -> DropCore {
    return try FfiConverterTypeDropCore.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDropCore_lower(_ value: DropCore) -> UnsafeMutableRawPointer {
    return FfiConverterTypeDropCore.lower(value)
}




public struct FfiChunkResult {
    public var msgId: String
    public var chunkIndex: UInt16
    public var totalChunks: UInt16
    public var isComplete: Bool
    public var assembledMessage: Data?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(msgId: String, chunkIndex: UInt16, totalChunks: UInt16, isComplete: Bool, assembledMessage: Data?) {
        self.msgId = msgId
        self.chunkIndex = chunkIndex
        self.totalChunks = totalChunks
        self.isComplete = isComplete
        self.assembledMessage = assembledMessage
    }
}

#if compiler(>=6)
extension FfiChunkResult: Sendable {}
#endif


extension FfiChunkResult: Equatable, Hashable {
    public static func ==(lhs: FfiChunkResult, rhs: FfiChunkResult) -> Bool {
        if lhs.msgId != rhs.msgId {
            return false
        }
        if lhs.chunkIndex != rhs.chunkIndex {
            return false
        }
        if lhs.totalChunks != rhs.totalChunks {
            return false
        }
        if lhs.isComplete != rhs.isComplete {
            return false
        }
        if lhs.assembledMessage != rhs.assembledMessage {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(msgId)
        hasher.combine(chunkIndex)
        hasher.combine(totalChunks)
        hasher.combine(isComplete)
        hasher.combine(assembledMessage)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiChunkResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiChunkResult {
        return
            try FfiChunkResult(
                msgId: FfiConverterString.read(from: &buf), 
                chunkIndex: FfiConverterUInt16.read(from: &buf), 
                totalChunks: FfiConverterUInt16.read(from: &buf), 
                isComplete: FfiConverterBool.read(from: &buf), 
                assembledMessage: FfiConverterOptionData.read(from: &buf)
        )
    }

    public static func write(_ value: FfiChunkResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.msgId, into: &buf)
        FfiConverterUInt16.write(value.chunkIndex, into: &buf)
        FfiConverterUInt16.write(value.totalChunks, into: &buf)
        FfiConverterBool.write(value.isComplete, into: &buf)
        FfiConverterOptionData.write(value.assembledMessage, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiChunkResult_lift(_ buf: RustBuffer) throws -> FfiChunkResult {
    return try FfiConverterTypeFfiChunkResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiChunkResult_lower(_ value: FfiChunkResult) -> RustBuffer {
    return FfiConverterTypeFfiChunkResult.lower(value)
}


public struct FfiDecryptedMessage {
    public var msgId: String
    public var senderId: Data
    public var msgType: String
    public var body: String
    public var timestampMs: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(msgId: String, senderId: Data, msgType: String, body: String, timestampMs: UInt64) {
        self.msgId = msgId
        self.senderId = senderId
        self.msgType = msgType
        self.body = body
        self.timestampMs = timestampMs
    }
}

#if compiler(>=6)
extension FfiDecryptedMessage: Sendable {}
#endif


extension FfiDecryptedMessage: Equatable, Hashable {
    public static func ==(lhs: FfiDecryptedMessage, rhs: FfiDecryptedMessage) -> Bool {
        if lhs.msgId != rhs.msgId {
            return false
        }
        if lhs.senderId != rhs.senderId {
            return false
        }
        if lhs.msgType != rhs.msgType {
            return false
        }
        if lhs.body != rhs.body {
            return false
        }
        if lhs.timestampMs != rhs.timestampMs {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(msgId)
        hasher.combine(senderId)
        hasher.combine(msgType)
        hasher.combine(body)
        hasher.combine(timestampMs)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiDecryptedMessage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiDecryptedMessage {
        return
            try FfiDecryptedMessage(
                msgId: FfiConverterString.read(from: &buf), 
                senderId: FfiConverterData.read(from: &buf), 
                msgType: FfiConverterString.read(from: &buf), 
                body: FfiConverterString.read(from: &buf), 
                timestampMs: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FfiDecryptedMessage, into buf: inout [UInt8]) {
        FfiConverterString.write(value.msgId, into: &buf)
        FfiConverterData.write(value.senderId, into: &buf)
        FfiConverterString.write(value.msgType, into: &buf)
        FfiConverterString.write(value.body, into: &buf)
        FfiConverterUInt64.write(value.timestampMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiDecryptedMessage_lift(_ buf: RustBuffer) throws -> FfiDecryptedMessage {
    return try FfiConverterTypeFfiDecryptedMessage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiDecryptedMessage_lower(_ value: FfiDecryptedMessage) -> RustBuffer {
    return FfiConverterTypeFfiDecryptedMessage.lower(value)
}


public struct FfiHandshakeInfo {
    public var deviceId: Data
    public var version: UInt8
    public var pendingMsgIds: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(deviceId: Data, version: UInt8, pendingMsgIds: [String]) {
        self.deviceId = deviceId
        self.version = version
        self.pendingMsgIds = pendingMsgIds
    }
}

#if compiler(>=6)
extension FfiHandshakeInfo: Sendable {}
#endif


extension FfiHandshakeInfo: Equatable, Hashable {
    public static func ==(lhs: FfiHandshakeInfo, rhs: FfiHandshakeInfo) -> Bool {
        if lhs.deviceId != rhs.deviceId {
            return false
        }
        if lhs.version != rhs.version {
            return false
        }
        if lhs.pendingMsgIds != rhs.pendingMsgIds {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(deviceId)
        hasher.combine(version)
        hasher.combine(pendingMsgIds)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiHandshakeInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiHandshakeInfo {
        return
            try FfiHandshakeInfo(
                deviceId: FfiConverterData.read(from: &buf), 
                version: FfiConverterUInt8.read(from: &buf), 
                pendingMsgIds: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiHandshakeInfo, into buf: inout [UInt8]) {
        FfiConverterData.write(value.deviceId, into: &buf)
        FfiConverterUInt8.write(value.version, into: &buf)
        FfiConverterSequenceString.write(value.pendingMsgIds, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiHandshakeInfo_lift(_ buf: RustBuffer) throws -> FfiHandshakeInfo {
    return try FfiConverterTypeFfiHandshakeInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiHandshakeInfo_lower(_ value: FfiHandshakeInfo) -> RustBuffer {
    return FfiConverterTypeFfiHandshakeInfo.lower(value)
}


public struct FfiIdentity {
    public var deviceId: Data
    public var publicKey: Data
    public var secretKey: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(deviceId: Data, publicKey: Data, secretKey: Data) {
        self.deviceId = deviceId
        self.publicKey = publicKey
        self.secretKey = secretKey
    }
}

#if compiler(>=6)
extension FfiIdentity: Sendable {}
#endif


extension FfiIdentity: Equatable, Hashable {
    public static func ==(lhs: FfiIdentity, rhs: FfiIdentity) -> Bool {
        if lhs.deviceId != rhs.deviceId {
            return false
        }
        if lhs.publicKey != rhs.publicKey {
            return false
        }
        if lhs.secretKey != rhs.secretKey {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(deviceId)
        hasher.combine(publicKey)
        hasher.combine(secretKey)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiIdentity: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiIdentity {
        return
            try FfiIdentity(
                deviceId: FfiConverterData.read(from: &buf), 
                publicKey: FfiConverterData.read(from: &buf), 
                secretKey: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: FfiIdentity, into buf: inout [UInt8]) {
        FfiConverterData.write(value.deviceId, into: &buf)
        FfiConverterData.write(value.publicKey, into: &buf)
        FfiConverterData.write(value.secretKey, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiIdentity_lift(_ buf: RustBuffer) throws -> FfiIdentity {
    return try FfiConverterTypeFfiIdentity.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiIdentity_lower(_ value: FfiIdentity) -> RustBuffer {
    return FfiConverterTypeFfiIdentity.lower(value)
}


public struct FfiMessage {
    public var msgId: String
    public var senderId: Data
    public var recipientId: Data
    public var timestampMs: UInt64
    public var wireBytes: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(msgId: String, senderId: Data, recipientId: Data, timestampMs: UInt64, wireBytes: Data) {
        self.msgId = msgId
        self.senderId = senderId
        self.recipientId = recipientId
        self.timestampMs = timestampMs
        self.wireBytes = wireBytes
    }
}

#if compiler(>=6)
extension FfiMessage: Sendable {}
#endif


extension FfiMessage: Equatable, Hashable {
    public static func ==(lhs: FfiMessage, rhs: FfiMessage) -> Bool {
        if lhs.msgId != rhs.msgId {
            return false
        }
        if lhs.senderId != rhs.senderId {
            return false
        }
        if lhs.recipientId != rhs.recipientId {
            return false
        }
        if lhs.timestampMs != rhs.timestampMs {
            return false
        }
        if lhs.wireBytes != rhs.wireBytes {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(msgId)
        hasher.combine(senderId)
        hasher.combine(recipientId)
        hasher.combine(timestampMs)
        hasher.combine(wireBytes)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiMessage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiMessage {
        return
            try FfiMessage(
                msgId: FfiConverterString.read(from: &buf), 
                senderId: FfiConverterData.read(from: &buf), 
                recipientId: FfiConverterData.read(from: &buf), 
                timestampMs: FfiConverterUInt64.read(from: &buf), 
                wireBytes: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: FfiMessage, into buf: inout [UInt8]) {
        FfiConverterString.write(value.msgId, into: &buf)
        FfiConverterData.write(value.senderId, into: &buf)
        FfiConverterData.write(value.recipientId, into: &buf)
        FfiConverterUInt64.write(value.timestampMs, into: &buf)
        FfiConverterData.write(value.wireBytes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiMessage_lift(_ buf: RustBuffer) throws -> FfiMessage {
    return try FfiConverterTypeFfiMessage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiMessage_lower(_ value: FfiMessage) -> RustBuffer {
    return FfiConverterTypeFfiMessage.lower(value)
}


public struct FfiPeer {
    public var deviceId: Data
    public var publicKey: Data
    public var displayName: String
    public var lastSeen: Int64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(deviceId: Data, publicKey: Data, displayName: String, lastSeen: Int64?) {
        self.deviceId = deviceId
        self.publicKey = publicKey
        self.displayName = displayName
        self.lastSeen = lastSeen
    }
}

#if compiler(>=6)
extension FfiPeer: Sendable {}
#endif


extension FfiPeer: Equatable, Hashable {
    public static func ==(lhs: FfiPeer, rhs: FfiPeer) -> Bool {
        if lhs.deviceId != rhs.deviceId {
            return false
        }
        if lhs.publicKey != rhs.publicKey {
            return false
        }
        if lhs.displayName != rhs.displayName {
            return false
        }
        if lhs.lastSeen != rhs.lastSeen {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(deviceId)
        hasher.combine(publicKey)
        hasher.combine(displayName)
        hasher.combine(lastSeen)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPeer: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPeer {
        return
            try FfiPeer(
                deviceId: FfiConverterData.read(from: &buf), 
                publicKey: FfiConverterData.read(from: &buf), 
                displayName: FfiConverterString.read(from: &buf), 
                lastSeen: FfiConverterOptionInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FfiPeer, into buf: inout [UInt8]) {
        FfiConverterData.write(value.deviceId, into: &buf)
        FfiConverterData.write(value.publicKey, into: &buf)
        FfiConverterString.write(value.displayName, into: &buf)
        FfiConverterOptionInt64.write(value.lastSeen, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPeer_lift(_ buf: RustBuffer) throws -> FfiPeer {
    return try FfiConverterTypeFfiPeer.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPeer_lower(_ value: FfiPeer) -> RustBuffer {
    return FfiConverterTypeFfiPeer.lower(value)
}


public enum DropError: Swift.Error {

    
    
    case Database(msg: String
    )
    case Crypto(msg: String
    )
    case InvalidData(msg: String
    )
    case PeerNotFound(deviceId: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDropError: FfiConverterRustBuffer {
    typealias SwiftType = DropError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DropError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Database(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Crypto(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 3: return .InvalidData(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 4: return .PeerNotFound(
            deviceId: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DropError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Database(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .Crypto(msg):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .InvalidData(msg):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .PeerNotFound(deviceId):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(deviceId, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDropError_lift(_ buf: RustBuffer) throws -> DropError {
    return try FfiConverterTypeDropError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDropError_lower(_ value: DropError) -> RustBuffer {
    return FfiConverterTypeDropError.lower(value)
}


extension DropError: Equatable, Hashable {}




extension DropError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt64: FfiConverterRustBuffer {
    typealias SwiftType = Int64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceData: FfiConverterRustBuffer {
    typealias SwiftType = [Data]

    public static func write(_ value: [Data], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterData.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Data] {
        let len: Int32 = try readInt(&buf)
        var seq = [Data]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterData.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiMessage: FfiConverterRustBuffer {
    typealias SwiftType = [FfiMessage]

    public static func write(_ value: [FfiMessage], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiMessage.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiMessage] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiMessage]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiMessage.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiPeer: FfiConverterRustBuffer {
    typealias SwiftType = [FfiPeer]

    public static func write(_ value: [FfiPeer], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiPeer.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiPeer] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiPeer]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiPeer.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_drop_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_drop_ffi_checksum_method_dropcore_add_peer() != 52402) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drop_ffi_checksum_method_dropcore_build_ack() != 64476) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drop_ffi_checksum_method_dropcore_build_bloom_filter() != 40261) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drop_ffi_checksum_method_dropcore_build_handshake() != 41581) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drop_ffi_checksum_method_dropcore_check_bloom_filter() != 46395) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drop_ffi_checksum_method_dropcore_compose_message() != 43307) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drop_ffi_checksum_method_dropcore_get_device_id() != 36057) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drop_ffi_checksum_method_dropcore_get_identity() != 32128) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drop_ffi_checksum_method_dropcore_get_peers() != 38685) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drop_ffi_checksum_method_dropcore_get_pending_for_peer() != 2641) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drop_ffi_checksum_method_dropcore_get_pending_recipients() != 7962) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drop_ffi_checksum_method_dropcore_mark_delivered() != 52255) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drop_ffi_checksum_method_dropcore_parse_handshake() != 36823) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drop_ffi_checksum_method_dropcore_process_chunk() != 25901) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drop_ffi_checksum_method_dropcore_receive_message() != 11303) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drop_ffi_checksum_method_dropcore_split_into_chunks() != 54931) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_drop_ffi_checksum_constructor_dropcore_new() != 2465) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureDropFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all